-- Guía y Traducción ES · textos propios del mod
-- Fichas en español que aparecen al pulsar cada mod en el menú «Mods»
-- (descriptions.Mod[<id del mod>]) y resúmenes de la pestaña «Guía».
return {
    descriptions = {
        Mod = {
            GuiaTraduccionES = {
                name = "Guía y Traducción ES",
                text = {
                    "{C:attention}Explica en español para qué sirve cada mod{}",
                    "y traduce al español lo que los mods",
                    "dejaron en inglés.",
                    " ",
                    "{C:green}Cómo usarlo:{} abre {C:attention}Mods{}, pulsa un mod",
                    "y lee su ficha. La pestaña {C:attention}Guía{} de este",
                    "mod resume todos tus mods instalados.",
                    " ",
                    "{C:inactive}No modifica los archivos de otros mods:{}",
                    "{C:inactive}las traducciones sobreviven a sus actualizaciones.{}",
                    " ",
                    "{C:inactive}v0.2 · Contacto: Instagram @_shun._05{}",
                },
            },
            Steamodded = {
                name = "Steamodded",
                text = {
                    "{C:attention}La base de todos los mods.{} Es el cargador",
                    "que permite que los demás mods funcionen",
                    "y añade el botón {C:attention}Mods{} del menú principal.",
                    " ",
                    "{C:green}Qué te aporta:{} lista de mods, activar o",
                    "desactivar cada uno, sus ajustes y créditos.",
                    " ",
                    "{C:red}No lo desactives:{} sin él no carga ningún mod.",
                },
            },
            Talisman = {
                name = "Talisman",
                text = {
                    "{C:attention}Rompe el límite de puntuación{} del juego",
                    "(números gigantes tipo {C:mult}e308{} y más allá)",
                    "y permite {C:attention}saltarse las animaciones{}",
                    "de puntuación para jugar más rápido.",
                    " ",
                    "{C:green}Ajustes:{} tipo de números (original,",
                    "BigNum u OmegaNum) y animaciones.",
                    "{C:inactive}Lo necesita Cryptid para funcionar.{}",
                },
            },
            Cryptid = {
                name = "Cryptid",
                text = {
                    "{C:attention}Expansión enorme y desequilibrada a propósito.{}",
                    "Cientos de comodines (épicos, {C:cry_exotic}exóticos{}...),",
                    "cartas {C:cry_code}Código{} (://), barajas, ciegas,",
                    "pegatinas y efectos con puntuaciones absurdas.",
                    " ",
                    "{C:green}Ajustes:{} conjunto de juego (moderado,",
                    "principal o locura) para controlar lo roto",
                    "que es. {C:inactive}Requiere Talisman.{}",
                },
            },
            Multiplayer = {
                name = "Multiplayer",
                text = {
                    "{C:attention}Juega contra tus amigos en línea.{}",
                    "Creas o te unes a una {C:attention}sala{} y competís",
                    "en partidas paralelas con ciegas {C:purple}PvP{}",
                    "contra tu {X:purple,C:white}Némesis{}.",
                    " ",
                    "{C:green}Incluye:{} modos (Desgaste, Enfrentamiento,",
                    "Supervivencia), reglas, temporizador, práctica,",
                    "repeticiones y comodines propios.",
                },
            },
            BetterSpanishLocale = {
                name = "BetterSpanishLocale",
                text = {
                    "{C:attention}Corrige la traducción oficial al español{}",
                    "de Balatro: errores, incoherencias y",
                    "términos mal traducidos del juego base.",
                    " ",
                    "{C:inactive}Funciona solo; no tiene opciones.{}",
                },
            },
            Bunco = {
                name = "Bunco",
                text = {
                    "{C:attention}Contenido nuevo con estilo «oficial».{}",
                    "Comodines, tarots, planetas, etiquetas,",
                    "vales, ciegas y mejoras (p. ej. cartas",
                    "{C:attention}petardo{} y cartas {C:attention}enlazadas{}).",
                    " ",
                    "{C:green}Extra:{} palos exóticos opcionales",
                    "({C:bunc_fleurons}florones{} y {C:bunc_halberds}alabardas{}) en sus ajustes.",
                },
            },
            CardSleeves = {
                name = "Card Sleeves (Fundas)",
                text = {
                    "{C:attention}Añade fundas para tus barajas.{}",
                    "Al empezar partida eliges baraja {C:attention}+ funda{}",
                    "y se suman ambos efectos.",
                    " ",
                    "{C:green}Truco:{} si eliges la funda de la misma",
                    "baraja, obtienes un efecto especial",
                    "mejorado. Se desbloquean ganando partidas.",
                },
            },
            cartomancer = {
                name = "Cartomancer",
                text = {
                    "{C:attention}Mejoras de comodidad y rendimiento.{}",
                    "Apila cartas repetidas al ver la baraja,",
                    "deja {C:attention}ver la tienda{} desde un paquete,",
                    "muestra el historial de ciegas jefe,",
                    "la última y la mejor puntuación...",
                    " ",
                    "{C:green}Ajustes:{} cada función se activa o",
                    "desactiva por separado.",
                },
            },
            galdur = {
                name = "Galdur",
                text = {
                    "{C:attention}Nuevo menú para empezar partida.{}",
                    "Elige baraja, pozo (y funda) en pantallas",
                    "más cómodas, con vista previa y",
                    "{C:attention}inicio rápido{}.",
                    " ",
                    "{C:inactive}Si molesta, se puede volver al selector{}",
                    "{C:inactive}original desde los ajustes de Steamodded.{}",
                },
            },
            joker_evolution = {
                name = "Joker Evolution",
                text = {
                    "{C:attention}Algunos comodines pueden evolucionar{}",
                    "a versiones mucho más fuertes.",
                    " ",
                    "{C:green}Cómo:{} cumple la condición del comodín",
                    "y usa el consumible de {C:attention}evolución{}",
                    "sobre él.",
                    "{C:inactive}Ajustes: evoluciones, consumibles y extras.{}",
                },
            },
            JokerDisplay = {
                name = "JokerDisplay",
                text = {
                    "{C:attention}Muestra información útil bajo cada comodín:{}",
                    "cuánto multi o fichas da ahora, contadores,",
                    "probabilidades, cartas que lo activan...",
                    " ",
                    "{C:green}Controles:{} clic derecho (o B) para",
                    "ocultar/mostrar; clic izquierdo (o arriba)",
                    "para plegar/desplegar.",
                },
            },
            kino = {
                name = "Balatro Goes Kino",
                text = {
                    "{C:attention}Comodines basados en películas.{}",
                    "Cada uno tiene géneros, reparto y director,",
                    "con sinergias entre ellos. Añade golosinas,",
                    "hechizos, contadores, ciegas de villanos",
                    "y cartas mejoradas por género.",
                    " ",
                    "{C:green}Teclas:{} {C:attention}S{} abre el libro de hechizos;",
                    "{C:attention}K{} sobre un comodín de Kino muestra su ficha.",
                },
            },
            malverk = {
                name = "Malverk",
                text = {
                    "{C:attention}Gestor de texturas.{} Te deja elegir",
                    "qué aspecto tiene cada tipo de carta",
                    "(comodines, tarots, barajas...) y aplicar",
                    "paquetes de texturas completos.",
                    " ",
                    "{C:green}Dónde:{} Opciones > {C:attention}Texturas{}.",
                    "{C:inactive}Lo usa Balatro Dark Mode.{}",
                },
            },
            darktextures = {
                name = "Balatro Dark Mode (texturas)",
                text = {
                    "{C:attention}Versión oscura de las cartas{} del juego:",
                    "comodines, etiquetas, barajas, sellos,",
                    "vales, paquetes, tarots y planetas.",
                    " ",
                    "{C:green}Cómo activarlo:{} Opciones > {C:attention}Texturas{}",
                    "(Malverk) > «Pack modo oscuro».",
                    "{C:inactive}Requiere Malverk.{}",
                },
            },
            BalatroDarkMode = {
                name = "Balatro Dark Mode (extras)",
                text = {
                    "{C:attention}Complemento del modo oscuro:{} cambia",
                    "los colores del fondo, de las ciegas",
                    "y de los palos, y oscurece la baraja,",
                    "la interfaz y el logo.",
                    " ",
                    "{C:inactive}Funciona solo; no tiene opciones.{}",
                },
            },
            BetterMouseAndGamepad = {
                name = "Better Mouse and Gamepad",
                text = {
                    "{C:attention}Controles más cómodos con ratón y mando.{}",
                    "Clic derecho mantenido: seleccionar varias",
                    "cartas arrastrando. Rueda arriba: {C:blue}jugar{};",
                    "rueda abajo: {C:red}descartar{}. Botón central:",
                    "menú (mantener: nueva partida).",
                    "Botones laterales: ordenar por palo/valor.",
                    "{C:inactive}Todo se ajusta en su configuración.{}",
                },
            },
            ortalab = {
                name = "Ortalab",
                text = {
                    "{C:attention}Balatro «al revés», como de otro universo.{}",
                    "150 comodines nuevos, 20 desafíos,",
                    "8 pozos, cartas de {C:attention}Lotería{}, {C:ortalab_zodiac}zodiaco{}",
                    "y {C:attention}mitos{}, nuevas ciegas y mucho más.",
                    " ",
                    "{C:inactive}Prácticamente una secuela de Balatro.{}",
                },
            },
            paperback = {
                name = "Paperback",
                text = {
                    "{C:attention}Expansión con estilo del juego original.{}",
                    "Comodines nuevos, {C:paperback_minor_arcana}arcanos menores{},",
                    "clips para cartas, nuevos planetas,",
                    "barajas y la mano {C:attention}Espectro{}.",
                    " ",
                    "{C:green}Ajustes:{} activa o desactiva partes",
                    "del contenido.",
                },
            },
            Pokermon = {
                name = "Pokermon",
                text = {
                    "{C:attention}Cada comodín es un Pokémon.{}",
                    "Evolucionan al cumplir condiciones, tienen",
                    "{C:poke_pink}tipos{}, se cargan con {C:attention}energía{} y",
                    "usan objetos (Poké Balls, piedras...).",
                    " ",
                    "{C:green}Ajustes:{} generaciones, sprites,",
                    "energía y opciones visuales.",
                },
            },
            SixSuits = {
                name = "Six Suits (Seis palos)",
                text = {
                    "{C:attention}Añade dos palos nuevos:{} estrellas y lunas.",
                    "Incluye la mano {C:attention}Espectro{} (cartas de",
                    "palos distintos) y sus planetas.",
                    " ",
                    "{C:green}Ajustes:{} permitir todos los palos",
                    "en la baraja o solo en algunas.",
                },
            },
            Solatro = {
                name = "Solatro",
                text = {
                    "{C:attention}Un solitario (Klondike) en el menú principal{}",
                    "hecho con las cartas de Balatro.",
                    " ",
                    "{C:green}Cómo jugar:{} arrastra cartas o grupos;",
                    "o haz clic para cogerlas y otra vez para",
                    "dejarlas. Doble clic: enviar a su base.",
                    "{C:inactive}Incluye la cascada de victoria clásica.{}",
                },
            },
            Handy = {
                name = "Handy",
                text = {
                    "{C:attention}Atajos y controles rápidos.{} Selecciona cartas",
                    "pasando el ratón, juega/descarta con teclas,",
                    "compra/vende/usa al instante, {C:attention}acelera{}",
                    "el juego y {C:attention}salta animaciones{}.",
                    " ",
                    "{C:green}Dónde:{} Opciones > botón {C:attention}Handy{}.",
                    "{C:inactive}Todo se puede asignar a teclado, ratón o mando.{}",
                },
            },
            JokerRunInfo = {
                name = "Joker Run Info",
                text = {
                    "{C:attention}Pestaña «Comodines» en Información de la partida:{}",
                    "qué da cada comodín ahora mismo, totales",
                    "y espacios ocupados.",
                    " ",
                    "{C:green}Truco:{} arrastra para reordenarlos;",
                    "el orden decide en qué orden se activan.",
                },
            },
            toomanyjokers = {
                name = "Too Many Jokers",
                text = {
                    "{C:attention}Buscador de cartas de todos tus mods.{}",
                    " ",
                    "{C:green}Uso:{} pulsa {C:attention}T{} y escribe palabras clave",
                    "separadas por comas (p. ej. «+multi, corazones»).",
                    "{C:inactive}Ideal para saber qué hace una carta concreta.{}",
                },
            },
            ShopUndo = {
                name = "Shop Undo",
                text = {
                    "{C:attention}Deshacer en la tienda.{} Tras cambiar la tienda,",
                    "recupera la fila anterior tal cual estaba.",
                    " ",
                    "{C:green}Uso:{} pulsa {C:attention}U{} o clic derecho en {C:green}Cambiar{};",
                    "repítelo para retroceder varios pasos.",
                },
            },
            ScrDesc = {
                name = "Scrollable Descriptions",
                text = {
                    "{C:attention}Mueve las descripciones que no caben{}",
                    "en pantalla (muy útil con Cryptid y Kino).",
                    " ",
                    "{C:green}Uso:{} flechas para mover, {C:attention}Inicio{} para",
                    "devolverlas a su sitio.",
                },
            },
            TheBindingOfJimbo = {
                name = "The Binding of Jimbo",
                text = {
                    "{C:attention}Balatro al estilo The Binding of Isaac.{}",
                    "Objetos {C:attention}activos{} y {C:attention}baratijas{} con zona propia,",
                    "cartas de botín, transformaciones, pecados",
                    "capitales como ciegas, barajas de personajes",
                    "(Isaac, Caín, Judas...) y pozos nuevos.",
                    "{C:inactive}Equilibrado como el juego original.{}",
                },
            },
            extracredit = {
                name = "Extra Credit",
                text = {
                    "{C:attention}45 comodines y 3 barajas de estilo original{}",
                    "creados por la comunidad Balatro University.",
                    " ",
                    "{C:inactive}Algunos también aparecen en el modo{}",
                    "{C:inactive}«Sandbox» de Multiplayer.{}",
                },
            },
            Bakery = {
                name = "Bakery",
                text = {
                    "{C:attention}Contenido variado con mecánicas únicas:{}",
                    "comodines (hombres lobo que cambian de día",
                    "a noche), {C:attention}amuletos{} equipables, barajas,",
                    "etiquetas, ciegas y manos de póker nuevas.",
                    "{C:inactive}Equilibrado como el juego original.{}",
                },
            },
            Prism = {
                name = "Prism",
                text = {
                    "{C:attention}Expansión de estilo original:{} cartas {C:attention}Mito{}",
                    "(nuevo consumible), 30+ comodines, mejoras,",
                    "sellos y barajas con sus {C:attention}fundas{} a juego.",
                    " ",
                    "{C:inactive}Aprovecha Card Sleeves si está activo.{}",
                },
            },
            LostEdition = {
                name = "Balatro: Lost Edition",
                text = {
                    "{C:attention}Expansión no oficial de cartas «perdidas».{}",
                    "Comodines misteriosos, ediciones nuevas",
                    "(como {C:dark_edition}plasma{}), espectrales, barajas",
                    "y sorpresas, con música propia.",
                },
            },
        },
    },
    misc = {
        dictionary = {
            guiaes_tab = "Guía",
            guiaes_titulo = "Tus mods instalados",
            guiaes_pagina = "Página",
            guiaes_contacto = "Contacto (Instagram)",
            guiaes_version = "Guía y Traducción ES v0.2",
            guiaes_ayuda = "Pulsa un mod en la lista de Mods para ver su ficha completa",
            guiaes_sin_resumen = "Sin resumen disponible",

            -- Resúmenes de una línea para la pestaña «Guía» (clave: guiaes_res_<id>)
            guiaes_res_Steamodded = "Cargador de mods: sin él no funciona ninguno",
            guiaes_res_Talisman = "Sin límite de puntuación y sin animaciones lentas",
            guiaes_res_Cryptid = "Contenido enorme y roto a propósito",
            guiaes_res_Multiplayer = "Partidas en línea contra amigos (PvP)",
            guiaes_res_BetterSpanishLocale = "Corrige la traducción española del juego",
            guiaes_res_Bunco = "Comodines, tarots y ciegas de estilo oficial",
            guiaes_res_CardSleeves = "Fundas que se combinan con tu baraja",
            guiaes_res_cartomancer = "Comodidades: apilar cartas, ver tienda...",
            guiaes_res_galdur = "Nuevo menú para elegir baraja y pozo",
            guiaes_res_joker_evolution = "Evoluciona comodines a versiones fuertes",
            guiaes_res_JokerDisplay = "Info en vivo bajo cada comodín",
            guiaes_res_kino = "Comodines de películas con sinergias",
            guiaes_res_malverk = "Gestor de texturas (Opciones > Texturas)",
            guiaes_res_darktextures = "Cartas en modo oscuro (vía Malverk)",
            guiaes_res_BalatroDarkMode = "Colores y fondo oscuros",
            guiaes_res_BetterMouseAndGamepad = "Atajos de ratón y mando",
            guiaes_res_ortalab = "Balatro alternativo: 150 comodines nuevos",
            guiaes_res_paperback = "Expansión: arcanos menores, clips...",
            guiaes_res_Pokermon = "Comodines Pokémon que evolucionan",
            guiaes_res_SixSuits = "Palos estrellas y lunas, mano Espectro",
            guiaes_res_Solatro = "Solitario en el menú principal",
            guiaes_res_LostEdition = "Cartas «perdidas» y ediciones nuevas",
            guiaes_res_GuiaTraduccionES = "Esta guía y las traducciones al español",
            guiaes_res_Handy = "Atajos, velocidad y saltar animaciones",
            guiaes_res_JokerRunInfo = "Pestaña «Comodines» en la info de partida",
            guiaes_res_toomanyjokers = "Buscador de cartas (tecla T)",
            guiaes_res_ShopUndo = "Deshacer cambios de tienda (tecla U)",
            guiaes_res_ScrDesc = "Mover descripciones largas con flechas",
            guiaes_res_TheBindingOfJimbo = "Contenido de The Binding of Isaac",
            guiaes_res_extracredit = "45 comodines de estilo original",
            guiaes_res_Bakery = "Amuletos, hombres lobo y manos nuevas",
            guiaes_res_Prism = "Cartas Mito y fundas a juego",
        },
    },
}
